### ISSUE TITLE
Question: Edge Detection

### ISSUE THREAD

**Issue by XinrunXu** [agentsea/robbie-g2#7]
Hello, guys!
I have seen your video on YouTube.
I want to know how you do  "Edge detection with open CV and Scikit-learn to find all the right bounding boxes", and where is the code.
Looking forward to your response~

**Comment by XinrunXu** [comment]
I have seen this in robbieg2/canny_composite.py.
However, it doesn't seem to be able to divide the interface into functional areas and blocks. 
Do you have any better-dividing method to recommend?
Thank you.

**Comment by mariyadavydova** [comment]
Hey @XinrunXu! I'm sorry for the late reply; I was on vacation :)) 

Indeed, the edge detection and splitting into blocks happen in `robbieg2/canny_composite.py`. 
You can see the steps we take at the end of the file:

```
    edges = improved_canny(image)
    grouped_contours = group_elements(edges)
    bounding_boxes = extract_bounding_boxes(grouped_contours)
    clustered_boxes = cluster_bounding_boxes(bounding_boxes, num_clusters)
    composite_image = create_composite_image(clustered_boxes, pil_image)
```

So, we find the edges using OpenCV, then we wrap those edges into bounding boxes (at this stage, you are likely to have several hundreds of bounding boxes), and then we cluster them. 

We use `Hierarchical clustering (Agglomerative Clustering)` from sklearn: this method simply merges the two closest boxes and then repeats this process until the resulting number of boxes is the one that we ask for. The benefit is that this method is dead simple, and we guarantee that we have any element fully in at least one bounding box. The drawback, though, is that sometimes the merged boxes altogether cover the entire screen. 

If you want to improve this part of Robbie's brain, I would recommend a few things:

* Play around with other algorithms clustering the bounding boxes - sklearn has a few, and we didn't explore them all.
* Add some heuristics: for example, we remove tiny bounding boxes, and you may also want to remove the ones that cover the entire screen because they don't bring any new information. 

Please let me know if you have any questions!
